# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

jobs:
 - jobs:
  timeoutInMinutes: 10
  steps:
  -bash: echo "This is my first job"

- jobs: SecondJob
  steps: "This is my Second Job"
